# Solving Linear Equation Systems (LES) <br>through Gauß Elimination by Pivoting


## All Necessary Imports

In [2]:
import numpy as np
from IPython.display import display, Markdown, Latex, Math

## An Example of a Linear Equation System ##

The matrix $M$ represents the **LES** resulting from **Kirchhoff's Laws** applied to an **electrical circuit**, which is discussed in the video tutorials of the **NunezPhysics YouTube channel**.

To understand how to derive the LES from Kirchhoff's Laws please **watch the video tutorials** of **NunezPhysics**:

* [Kirchhoff's Law Part 1](https://www.youtube.com/watch?v=zdE7xsbuNTg)
* [Kirchhoff's Law Part 2](https://www.youtube.com/watch?v=hlUW2u-z69g)

You can find additional comments on the [teawiki.net](https://teawiki.net/doku.php?id=eeng:topics:kirchhoff_s_circuit_laws:start) wiki page.



The correct form of the LES based of physical quantities would be **with units**:

$
\begin{pmatrix}
-1.0 & -1.0 & 1.0 \\ 
-6.0 & 3.0 & 0.0 \\ 
0.0 & -3.0 & -6.0 
\end{pmatrix}
\mathrm{Ohms}
\cdot \vec{I} = \begin{pmatrix} 0 \\ -24 \\ -12 \end{pmatrix}
\mathrm{Volts}
$

Without units is easier to read:

$
\begin{pmatrix}
-1.0 & -1.0 & 1.0 \\ 
-6.0 & 3.0 & 0.0 \\ 
0.0 & -3.0 & -6.0 
\end{pmatrix}
\vec{I} = 
\begin{pmatrix} 
0 \\ -24 \\ -12 
\end{pmatrix}
$


$
\begin{pmatrix}
-1.0 & -1.0 & 1.0 \\ 
-6.0 & 3.0 & 0.0 \\ 
0.0 & -3.0 & -6.0 
\end{pmatrix}
\begin{pmatrix}
I_1 \\ 
I_2 \\ 
I_3 
\end{pmatrix} = 
\begin{pmatrix} 
0 \\ -24 \\ -12 
\end{pmatrix}
$

The vector
$
\vec{I} = 
\begin{pmatrix}
I_1 \\ 
I_2 \\ 
I_3 
\end{pmatrix}
$
contains the three unknown currents of the circuit problem discussed in the videos.

## The LES Matrix in numpy

In [25]:
# A matrix is an array of rows, which are arrays. Thus a matrix is a two dimensional array.
# The numpy.array() function is used to create 2D array (aka matrix) from a list of row lists.
M = np.array(
    [
        [-1.0, -1.0,  1.0,   0.0],
        [-6.0,  3.0,  0.0, -24.0],
        [ 0.0, -3.0, -6.0, -12.0]
    ])


In [26]:
# What is in M?
M

array([[ -1.,  -1.,   1.,   0.],
       [ -6.,   3.,   0., -24.],
       [  0.,  -3.,  -6., -12.]])

In [27]:
# Nicer print output
print(M)

[[ -1.  -1.   1.   0.]
 [ -6.   3.   0. -24.]
 [  0.  -3.  -6. -12.]]


### Nice Matrix Rendering in Markdown ###

The rendered Markdown output generated from Python code makes the matrix representation even nicer. 

In [28]:
def Mat2MD(M, name="", idx="", fmt=""):
    '''
    2D numpy matrix to markdown code. 
    Generates a markdown string which can be rendered, e.g. by 
    IPython.display.display(Math(Mat2MD(M))).
    
    Parameters:
    M: 2D numpy array, the matrix
    name: matrix name to be used in the rendering, 
          e.g. name="A" renders to $A=...$
    idx: index of the matrix name, 
         e.g. idx="k" renders to $A_k=...$
    fmt: number format of the matrix elements, 
         e.g. fmt=".2f" print floating point format with 2 decimals.
    '''
    matrix_string = ""
    for r in M:
        if matrix_string: matrix_string += r" \\ "
#        fmt_string = f"{x}"
        matrix_string += " & ".join([f"{x:{fmt}}" for x in r])
    if name:
        if idx:
            Mstr = name + "_" + idx + "="
        else:
            Mstr = name + "="
    else:
        Mstr = ""

    return(Mstr + r"\begin{pmatrix}" + matrix_string + r"\end{pmatrix}")

In [41]:
help(Mat2MD)

Help on function Mat2MD in module __main__:

Mat2MD(M, name='', idx='', fmt='')
    2D numpy matrix to markdown code. 
    Generates a markdown string which can be rendered, e.g. by 
    IPython.display.display(Math(Mat2MD(M))).
    
    Parameters:
    M: 2D numpy array, the matrix
    name: matrix name to be used in the rendering, 
          e.g. name="A" renders to $A=...$
    idx: index of the matrix name, 
         e.g. idx="k" renders to $A_k=...$
    fmt: number format of the matrix elements, 
         e.g. fmt=".2f" print floating point format with 2 decimals.



In [35]:
print(M)
print()
print("Math string:")
print()
print(Mat2MD(M))
print()
display(Math(Mat2MD(M)))

[[ -1.  -1.   1.   0.]
 [ -6.   3.   0. -24.]
 [  0.  -3.  -6. -12.]]

Math string:

\begin{pmatrix}-1.0 & -1.0 & 1.0 & 0.0 \\ -6.0 & 3.0 & 0.0 & -24.0 \\ 0.0 & -3.0 & -6.0 & -12.0\end{pmatrix}



<IPython.core.display.Math object>

In [36]:
display(Math(Mat2MD(M)))
display(Math(Mat2MD(M,"A", fmt=".4f")))
display(Math(Mat2MD(M,"M_1"))) # subscript part of name
display(Math(Mat2MD(M,"M","3"))) # seperated subscript
display(Math(Mat2MD(M,"M","k")))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

### Nice Vector Rendering in Markdown ###

In [37]:
def Vec2MD(v, name="", idx="", fmt=""):
    '''
    2D numpy matrix to markdown code. 
    Generates a markdown string which can be rendered, e.g. by 
    IPython.display.display(Math(Mat2MD(M))).
    
    Parameters:
    v: 1D numpy array, the vector
    name: matrix name to be used in the rendering, 
          e.g. name="v" renders to $v=...$
    idx: index of the matrix name, 
         e.g. idx="k" renders to $v_k=...$
    fmt: number format of the matrix elements, 
         e.g. fmt=".2f" print floating point format with 2 decimals.
    '''
    matrix_string = ""
    for x in v:
        if matrix_string: matrix_string += r" \\ "
#        fmt_string = f"{x}"
        matrix_string += f"{x:{fmt}}"
    if name:
        if idx:
            Mstr = name + "_" + idx + "="
        else:
            Mstr = name + "="
    else:
        Mstr = ""

    return(Mstr + r"\begin{pmatrix}" + matrix_string + r"\end{pmatrix}")

In [38]:
v = np.array([  0., -24., -12.])
v
display(Math(Vec2MD(v)))

<IPython.core.display.Math object>

### Nice LES Rendering for Gauß Elimination ###

In [39]:
def Gauss2MD(M, name="", idx="", fmt="g"):
    '''
    2D numpy matrix to markdown code, output format for Gauß elimination.
    Generates a markdown string which can be rendered, e.g. by 
    IPython.display.display(Math(Gauss2MD(M))).
    
    Parameters:
    M: 2D numpy array, the matrix
    name: matrix name to be used in the rendering, 
          e.g. name="A" renders to $A=...$
    idx: index of the matrix name, 
         e.g. idx="k" renders to $A_k=...$
    fmt: number format of the matrix elements, 
         e.g. fmt=".2f" print floating point format with 2 decimals.
    '''
    matrix_string = ""
    for r in M:
#        if matrix_string: matrix_string += r" \\ "
        matrix_string += " & ".join([f"{x:{fmt}}" for x in r]) + r"\\"
    if name:
        if idx:
            Mstr = name + "_" + idx + "="
        else:
            Mstr = name + "="
    else:
        Mstr = ""
        
    (m,n) = M.shape
    fmt = "{"+(n-1)*"c"+"|"+"c"+"}"
    
    return(Mstr + r"\left(\begin{array}" + fmt + matrix_string + r"\end{array}\right)")

In [40]:
display(Math(Gauss2MD(M)))
display(Math(Gauss2MD(M,"A",fmt=".3f")))
display(Math(Gauss2MD(M,"M","1",fmt=".2e")))
display(Math(Gauss2MD(M,"M_k")))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [15]:
# Ordinary Python print output:
print("Ordinary Python print output:")
print(M)
print()

# Nice markdown redering:
print("Nice markdown rendering:")
display(Math(Gauss2MD(M,"M")))

Ordinary Python print output:
[[ -1.  -1.   1.   0.]
 [ -6.   3.   0. -24.]
 [  0.  -3.  -6. -12.]]

Nice markdown rendering:


<IPython.core.display.Math object>

## The Gauß Jordan Pivoting Algorithm 

Let us start with the matrix $A$:

$
A=\left(\begin{array}{ccc|c}-1 & -1 & 1 & 0\\-6 & 3 & 0 & -24\\0 & -3 & -6 & -12\\\end{array}\right)
$

Let us take two row vectors of matrix $A$, indicated by a single index:
<br>
$
A_0= (-1,\; -1,\; 1,\; 0)
$
<br>
$
A_1 = (-6,\; 3,\; 0,\; -24)
$

Element $0$ (column 0 of the matrix, the pivot column) of the row vectors (indicated by two indexes):
<br>
$
A_{0,0} = -1
$
<br>
$
A_{1,0} = -6
$

Normalization:

$
\begin{eqnarray}
\frac{A_0}{A_{0,0}} & = & (1,\; 1,\; -1,\; 0)
\\
\frac{A_1}{A_{1,0}} & = & (1,\; -0.5,\; 0,\; 4)
\end{eqnarray}
$


A **linear combination** of the row vectors is used to eliminate element $0$ of $A_1$:

$
\begin{eqnarray}
A^\mathrm{new}_1 & = & \frac{A_1}{A_{1,0}}-\frac{A_0}{A_{0,0}} 
= (1,\; -0.5,\; 0,\; 4) - (1,\; 1,\; -1,\; 0) 
= (0,\; -1.5,\; 1,\; 4)
\end{eqnarray}
$

Let us do the calculations it in Python:

In [16]:
# row 0 
print(M[0])

[-1. -1.  1.  0.]


In [17]:
# column 0 of row 0, column 0 is the current pivot column
print(M[0,0])

-1.0


In [18]:
# normalize row 0
print(M[0]/M[0,0])

[ 1.  1. -1. -0.]


In [19]:
# row 1 
print(M[1])

[ -6.   3.   0. -24.]


In [20]:
# column 0 of row 1, column 0 is the current pivot column
print(M[1,0])

-6.0


In [21]:
#normalize row 1
print(M[1]/M[1,0])

[ 1.  -0.5 -0.   4. ]


In [22]:
# subtract the normalized rows:
print(M[1]/M[1,0] - M[0]/M[0,0])

[ 0.  -1.5  1.   4. ]


The pivot element is eliminated. The result can be stored as the new row 0 or row 1 in the matrix.

### Gauss_Pivot(): The Pivoting Function to Create Row Echelon Form ###

**Let's create a function of automize the necessary operations!**

We need (1) the appropriate linear combination of two row vectors to eliminate the pivot element and (2) a normalization of rows (i.e. the division by an appropriate number) such that the pivot element becomes $1$. 

In [23]:
#def Gauss_Pivot(M,from_row,to_row,pivot_col,debug=False):
def Gauss_Pivot(M,row0,row1,col,debug=False):
    '''
    Function to perform operations typical for Gauß elimination.
    It returns a new matrix based on the operations.
    
    Parameters:
    M: 2D input matrix (2D numpy array)
    row0: matrix row index of the first row of the operation (0 based indexing)
    row1: matrix row index of the second row of the operation (0 based indexing)
          The result of the operation is stored in row1.
    col: pivot column index at which the second row is to be set to 0.
    
    Operation 1 (initiated if row0 != row1): linear combination of rows, elimination of pivot elt.
               M[row1] = M[row1]/M[row1,col] - = M[row0]/M[row0,col]
               
    Operation 2 (initiated if row0 == row1): normalize the row
               M[row1] = M[row1]/M[row1,col]
    '''
    MM=M.copy()
    
    (m,n)=MM.shape # can be used later ...

    # old version:
    # r = MM[row1,col] / MM[row2,col]
    # MM[row2] = MM[row1] - r*MM[row2]
    
    if row0 != row1: # linear combination
        MM[row1] = MM[row1]/MM[row1,col] - MM[row0]/MM[row0,col]
    else: # row normalization, row is devided by its pivot element
        MM[row1] = MM[row1]/MM[row1,col]

    if debug:
        print(MM[row0])
        print(MM[row1])
        print(MM[row0,col])
        print(MM[row1,col])    
        print(MM[row0]/MM[row0,col])
        print(MM[row1]/MM[row1,col])

    return(MM)

In [54]:
help(Gauss_Pivot)

Help on function Gauss_Pivot in module __main__:

Gauss_Pivot(M, row0, row1, col, debug=False)
    Function to perform operations typical for Gauß elimination.
    It returns a new matrix based on the operations.
    
    Parameters:
    M: 2D input matrix (2D numpy array)
    row0: matrix row index of the first row of the operation (0 based indexing)
    row1: matrix row index of the second row of the operation (0 based indexing)
          The result of the operation is stored in row1.
    col: pivot column index at which the second row is to be set to 0.
    
    Operation 1 (initiated if row0 != row1): linear combination of rows, elimination of pivot elt.
               M[row1] = M[row1]/M[row1,col] - = M[row0]/M[row0,col]
               
    Operation 2 (initiated if row0 == row1): normalize the row
               M[row1] = M[row1]/M[row1,col]



### Gauss_Pivot2(): Another Version of the Linear Combination of Rows

In [24]:
def Gauss_Pivot2(M,row0,f0,row1,f1,row2,debug=False):
    '''
    Function to perform operations typical for Gauß elimination.
    It returns a new matrix based on the operations.
    row2 <- f0*row0 + f1*row1
    
    Parameters:
    M: 2D input matrix (2D numpy array)
    row0: matrix row index of the first row of the operation (0 based indexing)
    f0:   linear factor for row0
    row1: matrix row index of the second row of the operation (0 based indexing)
    f1:   linear factor for row1
    row2: the result of the operation is stored in row2.
    
    Example:
    M2 = Gauss_Pivot2(M1,0,1,2,-1/3,2) # operation on rows: M1[0]*1 + M1[2]*(-1/3) -> M1[2]
    '''

    MM=M.copy().astype(np.float64) # (double precision float)
    
    (m,n)=MM.shape # can be used later ...

    res = f0*MM[row0] + f1*MM[row1] 

    if debug:
        print(f"MM[{row0}] = {MM[row0]}")
        print(f"MM[{row1}] = {MM[row1]}")
        print(f"f0*MM[{row0}] = {f0*MM[row0]}")
        print(f"f1*MM[{row1}] = {f1*MM[row1]}")
        print(f"MM[{row2}] = {res}")
        
    MM[row2] = res
    
    return(MM)

## Apply the Pivoting Function to Achieve the Row Echelon Form of the Matrix

In [55]:
display(Math(Gauss2MD(M,"M")))

<IPython.core.display.Math object>

In [56]:
M1 = Gauss_Pivot(M,0,1,0)
display(Math(Gauss2MD(M1,"M_1")))

<IPython.core.display.Math object>

In [57]:
M2 = Gauss_Pivot(M1,1,2,1)
display(Math(Gauss2MD(M2,"M_2", fmt=".4f")))

<IPython.core.display.Math object>

In [58]:
print(f"{2 + 2/3:.4f}")
print(f"{6 + 2/3:.4f}")

2.6667
6.6667


**This is already the row echelon form!**
<br>
But let us go on! 
<br>
Now we work from last row to first row to diagonalize the left part.

In [59]:
# normalize row 2
M3 = Gauss_Pivot(M2,2,2,2)
display(Math(Gauss2MD(M3,"M_3")))

<IPython.core.display.Math object>

In [60]:
# row 2 -> row 1, pivot column 2
M4 = Gauss_Pivot(M3,2,1,2)
display(Math(Gauss2MD(M4,"M_4")))

<IPython.core.display.Math object>

In [61]:
# normalize row 1, pivot column 1
M5 = Gauss_Pivot(M4,1,1,1)
display(Math(Gauss2MD(M5,"M_5")))

<IPython.core.display.Math object>

In [62]:
# row 2 -> row 0, pivot column 2
M6 = Gauss_Pivot(M5,2,0,2)
display(Math(Gauss2MD(M6,"M_6")))

<IPython.core.display.Math object>

In [63]:
# row 1 -> row 0, pivot column 1
M7 = Gauss_Pivot(M6,1,0,1)
display(Math(Gauss2MD(M7,"M_7")))

<IPython.core.display.Math object>

In [64]:
# normalize row 0
M8 = Gauss_Pivot(M7,0,0,0)
display(Math(Gauss2MD(M8,"M_8")))

<IPython.core.display.Math object>

### Final Results

**The final result reads:**

$
\left(\begin{array}{ccc}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1 \\
\end{array}\right)
\left(\begin{array}{c}
I_1 \\
I_2 \\
I_3 \\
\end{array}\right) =
\left(\begin{array}{c}
3.5 \\
-1 \\
2.5 \\
\end{array}\right)
$

i.e.
<br>
$1\cdot I_1 + 0\cdot I_2 + 0\cdot I_3 = 3.5$, etc.
<br>
$\Leftrightarrow$ 
<br>
$I_1 = 3.5\mathrm{A}$
<br>
$I_2 = -1\mathrm{A}$
<br>
$I_3 = 2.5\mathrm{A}$

## Smart Solution by Matrix Inversion

In [65]:
display(Math(Gauss2MD(M)))
display(Math(Mat2MD(M,name="M")))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

**Extract the Resistance Matrix**

In [66]:
R = M[:,:-1]
display(Math(Mat2MD(R,name=r"{\bf R}")))

<IPython.core.display.Math object>

**Extract the Voltage Vector**

In [67]:
V = M[:,-1]
display(Math(Vec2MD(V,name=r"\vec{V}")))

<IPython.core.display.Math object>

**The LES:**

${\bf R} \vec{I} = \vec{V}$

The inverse matrix ${\bf R^{^-1}}$ is another matrix with the following property:

$$
{\bf R^{^-1} R} = \mathbb{1} = \begin{pmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{pmatrix}
$$

Sometimes such a matrix called $\bf R^{^-1}$ does not exist. Not all matrices ${\bf R}$ have an inverse.
<br>
If the inverse matrix ${\bf R^{^-1}}$ exists then the matrix multiplication of ${\bf R^{^-1}}$ and ${\bf R}$ yields the unit matrix (aka identity matrix). You have to find the matrix ${\bf R^{^-1}}$ such that this works. 

If ${\bf R^{^-1}}$ exists, then we can multiply it **from the left side** to the LES equation above (notice: matrix-matrix multiplications are generally not commutative, i.e. ${\bf AB \neq BA}$):

$
\begin{eqnarray}
{\bf R^{^-1}}{\bf R} \vec{I} & = & {\bf R^{^-1}}\vec{V} 
 \Leftrightarrow \mathbb{1}\vec{I} = {\bf R^{^-1}}\vec{V} 
 \Leftrightarrow \vec{I} = {\bf R^{^-1}}\vec{V}
\end{eqnarray}
$

This means if we find the matrix ${\bf R^{^-1}}$ we can determine $\vec{I}$ by a simple vector matrix multiplication:

$$
\vec{I} = {\bf R^{^-1}}\vec{V}
$$

**Numpy provides nice functions from linear algebra to find the inverse matrix if it exists!**

In [68]:
Rinv = np.linalg.inv(R)
display(Math(Mat2MD(Rinv,name=r"{\bf R^{-1}}", fmt = ".4f")))

<IPython.core.display.Math object>

In [69]:
# TEST!
T = Rinv.dot(R)
display(Math(Mat2MD(T,name=r"{\bf T = R^{-1}R}", fmt = ".4f")))

<IPython.core.display.Math object>

The test shows: $\bf R^{^-1}$ is indeed the inverse of ${\bf R}$ because the product is the identity.

Now let us solve $\vec{I} = {\bf R^{^-1}}\vec{V}$

In [70]:
I = Rinv.dot(V)

In [72]:
display(Math(Vec2MD(I, name="I")))

<IPython.core.display.Math object>

**Yeppeee!!!**

### Summarized Matrix Inversion

Solve Kirchhoff's problem: $\vec{I} = {\bf R^{^-1}}\vec{V}$

BTW, it look like Ohm's law: $I=\frac{1}{R}V$

In [52]:
import numpy as np

# A matrix is an array of rows, which are arrays. Thus a matrix is a two dimensional array.
# The numpy.array() function is used to create 2D array (aka matrix) from a list of row lists.
R = np.array(
    [
        [-1.0, -1.0,  1.0],
        [-6.0,  3.0,  0.0],
        [ 0.0, -3.0, -6.0]
    ])

V = np.array([0.0, -24.0, -12.0])

# Inverse matrix
Rinv = np.linalg.inv(R)

# Matrix vector multiplication, aka dot product
I = Rinv.dot(V)

# Print currents
print(I)

[ 3.5 -1.   2.5]
