In [19]:
import numpy as np
from numpy.linalg import inv

In [22]:
R = np.array([[-1,-1,1],[-6,3,0],[0,-3,-6]])
R

array([[-1, -1,  1],
       [-6,  3,  0],
       [ 0, -3, -6]])

In [35]:
V = np.array([0,-24,-12])
V

array([  0, -24, -12])

In [31]:
Rinv = inv(R)
Rinv

array([[-0.25      , -0.125     , -0.04166667],
       [-0.5       ,  0.08333333, -0.08333333],
       [ 0.25      , -0.04166667, -0.125     ]])

In [32]:
(R.dot(Rinv))

array([[ 1.00000000e+00,  6.93889390e-18,  0.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00, -1.38777878e-17,  1.00000000e+00]])

In [34]:
I = Rinv.dot(V)
I

array([ 3.5, -1. ,  2.5])

In [40]:
print(f"{2*60*60*24*365*80:g}")

5.04576e+09


In [41]:
1/1.602

0.6242197253433208